language: node_js
node_js:
  - "stable"
cache:
  npm: true
  directories:
    - node_modules
install:
    - npm ci
script:
  - npm run deploy-travis
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN_3
  local_dir: build
  on:
    branch: master